/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RulesRulesRouteImport } from './routes/_rules/rules'
import { Route as ImpressumImpressumRouteImport } from './routes/_impressum/impressum'
import { Route as HistoryHistoryRouteImport } from './routes/_history/history'
import { Route as GameGameRouteImport } from './routes/_game/game'
import { Route as AboutAboutRouteImport } from './routes/_about/about'
import { Route as SignUpSignUpSplatRouteImport } from './routes/_sign-up/sign-up.$'
import { Route as SignInSignInSplatRouteImport } from './routes/_sign-in/sign-in.$'
import { Route as AuthenticatedDashboardDashboardRouteImport } from './routes/_authenticated/_dashboard/dashboard'

const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RulesRulesRoute = RulesRulesRouteImport.update({
  id: '/_rules/rules',
  path: '/rules',
  getParentRoute: () => rootRouteImport,
} as any)
const ImpressumImpressumRoute = ImpressumImpressumRouteImport.update({
  id: '/_impressum/impressum',
  path: '/impressum',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryHistoryRoute = HistoryHistoryRouteImport.update({
  id: '/_history/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const GameGameRoute = GameGameRouteImport.update({
  id: '/_game/game',
  path: '/game',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutAboutRoute = AboutAboutRouteImport.update({
  id: '/_about/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const SignUpSignUpSplatRoute = SignUpSignUpSplatRouteImport.update({
  id: '/_sign-up/sign-up/$',
  path: '/sign-up/$',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInSignInSplatRoute = SignInSignInSplatRouteImport.update({
  id: '/_sign-in/sign-in/$',
  path: '/sign-in/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardDashboardRoute =
  AuthenticatedDashboardDashboardRouteImport.update({
    id: '/_dashboard/dashboard',
    path: '/dashboard',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutAboutRoute
  '/game': typeof GameGameRoute
  '/history': typeof HistoryHistoryRoute
  '/impressum': typeof ImpressumImpressumRoute
  '/rules': typeof RulesRulesRoute
  '/dashboard': typeof AuthenticatedDashboardDashboardRoute
  '/sign-in/$': typeof SignInSignInSplatRoute
  '/sign-up/$': typeof SignUpSignUpSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutAboutRoute
  '/game': typeof GameGameRoute
  '/history': typeof HistoryHistoryRoute
  '/impressum': typeof ImpressumImpressumRoute
  '/rules': typeof RulesRulesRoute
  '/dashboard': typeof AuthenticatedDashboardDashboardRoute
  '/sign-in/$': typeof SignInSignInSplatRoute
  '/sign-up/$': typeof SignUpSignUpSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/_about/about': typeof AboutAboutRoute
  '/_game/game': typeof GameGameRoute
  '/_history/history': typeof HistoryHistoryRoute
  '/_impressum/impressum': typeof ImpressumImpressumRoute
  '/_rules/rules': typeof RulesRulesRoute
  '/_authenticated/_dashboard/dashboard': typeof AuthenticatedDashboardDashboardRoute
  '/_sign-in/sign-in/$': typeof SignInSignInSplatRoute
  '/_sign-up/sign-up/$': typeof SignUpSignUpSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/game'
    | '/history'
    | '/impressum'
    | '/rules'
    | '/dashboard'
    | '/sign-in/$'
    | '/sign-up/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/game'
    | '/history'
    | '/impressum'
    | '/rules'
    | '/dashboard'
    | '/sign-in/$'
    | '/sign-up/$'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/_about/about'
    | '/_game/game'
    | '/_history/history'
    | '/_impressum/impressum'
    | '/_rules/rules'
    | '/_authenticated/_dashboard/dashboard'
    | '/_sign-in/sign-in/$'
    | '/_sign-up/sign-up/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AboutAboutRoute: typeof AboutAboutRoute
  GameGameRoute: typeof GameGameRoute
  HistoryHistoryRoute: typeof HistoryHistoryRoute
  ImpressumImpressumRoute: typeof ImpressumImpressumRoute
  RulesRulesRoute: typeof RulesRulesRoute
  SignInSignInSplatRoute: typeof SignInSignInSplatRoute
  SignUpSignUpSplatRoute: typeof SignUpSignUpSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_rules/rules': {
      id: '/_rules/rules'
      path: '/rules'
      fullPath: '/rules'
      preLoaderRoute: typeof RulesRulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_impressum/impressum': {
      id: '/_impressum/impressum'
      path: '/impressum'
      fullPath: '/impressum'
      preLoaderRoute: typeof ImpressumImpressumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_history/history': {
      id: '/_history/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_game/game': {
      id: '/_game/game'
      path: '/game'
      fullPath: '/game'
      preLoaderRoute: typeof GameGameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_about/about': {
      id: '/_about/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutAboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_sign-up/sign-up/$': {
      id: '/_sign-up/sign-up/$'
      path: '/sign-up/$'
      fullPath: '/sign-up/$'
      preLoaderRoute: typeof SignUpSignUpSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_sign-in/sign-in/$': {
      id: '/_sign-in/sign-in/$'
      path: '/sign-in/$'
      fullPath: '/sign-in/$'
      preLoaderRoute: typeof SignInSignInSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/_dashboard/dashboard': {
      id: '/_authenticated/_dashboard/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardDashboardRoute: typeof AuthenticatedDashboardDashboardRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardDashboardRoute: AuthenticatedDashboardDashboardRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AboutAboutRoute: AboutAboutRoute,
  GameGameRoute: GameGameRoute,
  HistoryHistoryRoute: HistoryHistoryRoute,
  ImpressumImpressumRoute: ImpressumImpressumRoute,
  RulesRulesRoute: RulesRulesRoute,
  SignInSignInSplatRoute: SignInSignInSplatRoute,
  SignUpSignUpSplatRoute: SignUpSignUpSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
